# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hs5_lpWThWjroIADu1C-Q3ciJ1RRQEUv
"""

import pandas as pd
import numpy as np
import networkx as nx
from networkx.algorithms import community

# --- STEP 1: Create Dummy Continuous Production Data ---
# Simulating 3 machines over time running various recipes
np.random.seed(42)
num_rows = 15
recipes = ['R_Alpha', 'R_Beta', 'R_Gamma', 'R_Delta', 'R_Isolated']

df_raw = pd.DataFrame({
    'Datetime': pd.date_range(start='2026-09-20 00:00:00', periods=num_rows, freq='h'),
    'machine_id': np.random.choice(['M1', 'M2', 'M3'], size=num_rows),
    'recipe_id': np.random.choice(recipes, size=num_rows),
    'lot_id': [f'LOT_{100+i}' for i in range(num_rows)],
    'lot_qty': np.random.randint(50, 500, size=num_rows)
})

# --- STEP 2: Shift Rows within Machine Groups ---
# Sort chronologically to map exact sequential handoffs
df_sorted = df_raw.sort_values(by='Datetime').copy()

# Group by machine so recipes on Machine 1 don't shift into Machine 2
df_sorted['next_recipe_id'] = df_sorted.groupby('machine_id')['recipe_id'].shift(-1)

# Drop rows where next_recipe_id is NaN (the last run for each machine)
df_transitions = df_sorted.dropna(subset=['next_recipe_id']).copy()


# --- STEP 3: Compute the Transition Probability Matrix ---
# Count occurrences of every transition pair
counts = pd.crosstab(df_transitions['recipe_id'], df_transitions['next_recipe_id'])

# Re-index to guarantee a perfectly square matrix (rows match columns)
all_unique_recipes = sorted(list(set(df_raw['recipe_id'].unique())))
counts = counts.reindex(index=all_unique_recipes, columns=all_unique_recipes, fill_value=0)

# Normalize across rows to get transition probabilities (row sum = 1.0)
# Use clip(lower=1) to prevent division-by-zero on recipes that are only at the tail end of lines
transition_matrix = counts.div(counts.sum(axis=1).clip(lower=1), axis=0)

print("--- Transition Probability Matrix ---")
print(transition_matrix.round(2))
print("\n" + "="*50 + "\n")


# --- STEP 4: Build NetworkX Directed Graph ---
G = nx.DiGraph()

# Add edges only where a structural transition actually occurred
for from_recipe in transition_matrix.index:
    for to_recipe in transition_matrix.columns:
        prob = transition_matrix.loc[from_recipe, to_recipe]
        if prob > 0:
            G.add_edge(from_recipe, to_recipe, weight=prob)


# --- STEP 5: Detect Hard Boundaries & Closed Classes ---
print("--- HARD BOUNDARIES & ISOLATED CLUSTERS ---")

# 1. Catch strictly closed subgroups (Attracting Components)
closed_subgroups = list(nx.attracting_components(G))
for i, group in enumerate(closed_subgroups, 1):
    print(f"Closed Recipe Subgroup {i}: {list(group)}")

# 2. Catch individual recipes that only loop back to themselves
for node in G.nodes():
    successors = list(G.successors(node))
    if successors == [node]:
        print(f"Recipe '{node}' is trapped in a self-loop (never transitions to others).")


# --- STEP 6: Detect Soft Communities ---
print("\n--- SOFT COMMUNITIES (Tightly Coupled Groups) ---")
# Louvain maximizes internal transition weights over external leakages
soft_communities = community.louvain_communities(G, weight='weight', seed=42)
for i, comm in enumerate(soft_communities, 1):
    print(f"Soft Community Profile {i}: {list(comm)}")

df_sorted

counts

transition_matrix

import pandas as pd
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
from networkx.algorithms import community

# ==========================================
# STEP 1: GENERATE CONTINUOUS RAW PRODUCTION DATA
# ==========================================
np.random.seed(42)
num_rows = 30
recipes = ['R_Alpha', 'R_Beta', 'R_Gamma', 'R_Delta', 'R_Isolated']
machines = ['Machine_1', 'Machine_2']

# Simulate an active factory timeline over a few days
time_range = pd.date_range(start='2026-09-20 00:00:00', periods=num_rows, freq='3h')

df_raw = pd.DataFrame({
    'Datetime': np.random.choice(time_range, size=num_rows, replace=False), # Out of order
    'machine_id': np.random.choice(machines, size=num_rows),
    'recipe_id': np.random.choice(recipes, size=num_rows),
    'lot_id': [f'LOT_{100+i}' for i in range(num_rows)],
    'lot_qty': np.random.randint(50, 500, size=num_rows)
})

# Ensure Datetime format
df_raw['Datetime'] = pd.to_datetime(df_raw['Datetime'])


# ==========================================
# STEP 2: SHIFT AND FILTER BY DOWNTIME GAP
# ==========================================
# Define maximum time allowed to count as a back-to-back transition
MAX_GAP = pd.Timedelta(hours=12)

# Sort chronologically to track true physical sequence
df_sorted = df_raw.sort_values(by='Datetime').copy()

# Group by machine to keep transition threads isolated
df_group = df_sorted.groupby('machine_id')

# Shift subsequent recipe and its execution timestamp
df_sorted['next_recipe_id'] = df_group['recipe_id'].shift(-1)
df_sorted['next_datetime'] = df_group['Datetime'].shift(-1)

# Calculate elapsed time between lots
df_sorted['time_elapsed'] = df_sorted['next_datetime'] - df_sorted['Datetime']

# Keep rows where a next recipe exists AND the transition gap is close enough
valid_transition_mask = (
    df_sorted['next_recipe_id'].notna() &
    (df_sorted['time_elapsed'] <= MAX_GAP)
)
df_transitions = df_sorted[valid_transition_mask].copy()


# ==========================================
# STEP 3: COMPUTE THE TRANSITION PROBABILITY MATRIX
# ==========================================
# Cross-tabulate occurrences of every transition pair
counts = pd.crosstab(df_transitions['recipe_id'], df_transitions['next_recipe_id'])

# Guarantee a completely square matrix across all active recipe IDs
all_unique_recipes = sorted(list(df_raw['recipe_id'].unique()))
counts = counts.reindex(index=all_unique_recipes, columns=all_unique_recipes, fill_value=0)

# Normalize row-wise to find probabilities (Sum of row = 1.0)
transition_matrix = counts.div(counts.sum(axis=1).clip(lower=1), axis=0)

print("--- Transition Probability Matrix ---")
print(transition_matrix.round(2))
print("\n" + "="*50 + "\n")


# ==========================================
# STEP 4: GENERATE THE NETWORKX DIRECTED GRAPH
# ==========================================
G = nx.DiGraph()

# Feed matrix relationships into network edges
for from_recipe in transition_matrix.index:
    for to_recipe in transition_matrix.columns:
        prob = transition_matrix.loc[from_recipe, to_recipe]
        if prob > 0:
            G.add_edge(from_recipe, to_recipe, weight=prob)


# ==========================================
# STEP 5: RUN NETWORK ANALYTICS SUBGROUP DETECTION
# ==========================================
print("--- SUBGROUP & COMMUNITY DETECTION ---")

# 1. Catch strictly closed subgroups (Attracting Components)
closed_subgroups = list(nx.attracting_components(G))
for i, group in enumerate(closed_subgroups, 1):
    print(f"Hard Boundary Subgroup {i} (Closed Class): {list(group)}")

# 2. Catch individual recipes trapped inside self-loops
for node in G.nodes():
    successors = list(G.successors(node))
    if successors == [node]:
        print(f"Self-Isolated Node: '{node}' loops into itself and never exits.")

# 3. Soft Communities via Louvain Modularity Clustering
soft_communities = community.louvain_communities(G, weight='weight', seed=42)
for i, comm in enumerate(soft_communities, 1):
    print(f"Soft Connected Community {i}: {list(comm)}")


# ==========================================
# STEP 6: VISUALIZE RELATIONSHIPS
# ==========================================
plt.figure(figsize=(10, 7))

# Calculate spatial layout positioning (spring layout spaces clusters nicely)
pos = nx.spring_layout(G, k=1.2, seed=42)

# Dynamic coloring map based on Louvain community assignment
community_map = {}
for i, comm in enumerate(soft_communities):
    for node in comm:
        community_map[node] = i
colors = [community_map[node] for node in G.nodes()]

# Draw the infrastructure nodes
nx.draw_networkx_nodes(G, pos, node_size=1200, node_color=colors, cmap=plt.cm.Set3, edgecolors='black')

# Separate self-loops from directional arrows to keep the visual neat
standard_edges = [(u, v) for u, v in G.edges() if u != v]
self_loops = [(u, v) for u, v in G.edges() if u == v]

# Draw standard directed lines between recipes
nx.draw_networkx_edges(G, pos, edgelist=standard_edges, arrowstyle='->', arrowsize=20,
                       edge_color='gray', width=1.5, connectionstyle='arc3,rad=0.15')

# Draw circular arrows for self-transitions
nx.draw_networkx_edges(G, pos, edgelist=self_loops, arrowstyle='->', arrowsize=15,
                       edge_color='darkred', width=1.0, connectionstyle='arc3,rad=0.4')

# Label nodes with recipe names
nx.draw_networkx_labels(G, pos, font_size=10, font_weight='bold')

# Pull weight metrics to label lines with their transition probability percentages
edge_labels = {(u, v): f"{G[u][v]['weight']:.2f}" for u, v in standard_edges}
nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels, font_size=8, label_pos=0.3)

plt.title("Recipe Transition Probability Network Map\n(Colors indicate Soft Communities | Red loops indicate self-transitions)", fontsize=12, fontweight='bold')
plt.axis('off')
plt.tight_layout()
plt.show()

# ==========================================
# STEP 7: GENERATE AND EXPORT SUMMARY REPORT
# ==========================================

report_data = []

# Map soft communities for fast lookup
community_map = {node: f"Community {i}" for i, comm in enumerate(soft_communities, 1) for node in comm}

for node in all_unique_recipes:
    # 1. Determine Hard Boundary Status
    hard_group_id = "None"
    for i, group in enumerate(closed_subgroups, 1):
        if node in group:
            # If the size of the closed group is 1, it's a completely isolated loop
            hard_group_id = f"Closed Group {i}" if len(group) > 1 else "Self-Isolated"
            break

    # 2. Check if it's a structural Dead End (Sink node)
    # If the node has no outgoing edges in the graph, it has a 0 probability row
    is_dead_end = G.out_degree(node) == 0

    # 3. Collect neighbors it interacts with
    successors = list(G.successors(node)) if node in G else []

    # Compile row details
    report_data.append({
        'Recipe_ID': node,
        'Soft_Community_Assignment': community_map.get(node, "Unassigned"),
        'Hard_Boundary_Status': hard_group_id,
        'Is_Dead_End_Sink': "Yes (0% Exit Probability)" if is_dead_end else "No",
        'Unique_Transitions_To': ", ".join(successors) if successors else "None"
    })

# Convert to Pandas DataFrame
df_report = pd.DataFrame(report_data)

# Export to a CSV spreadsheet file
output_filename = "recipe_network_summary.csv"
# df_report.to_csv(output_filename, index=False)

print(f"\n--- Summary Report Successfully Generated: '{output_filename}' ---")
print(df_report.to_string(index=False))

import pandas as pd
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt
from networkx.algorithms import community

# ==========================================
# STEP 1: GENERATE LARGE SCALED PRODUCTION DATA
# ==========================================
np.random.seed(42)

# 20 Recipes, 10 Machines, ~110 rows per machine
recipes = [f'R_{i:02d}' for i in range(1, 21)]
machines = [f'Machine_{i:02d}' for i in range(1, 11)]

df_list = []
start_time = pd.Timestamp('2026-09-01 00:00:00')

# Simulate continuous timelines per machine
for m in machines:
    # Generate 110 records per machine
    m_times = sorted([start_time + pd.Timedelta(hours=int(x)) for x in np.random.choice(range(500), size=110, replace=False)])

    # Assign recipes with structural affinities to create realistic clusters
    if m in machines[0:4]:     # Machines 1-4 specialize in R_01 to R_08
        m_recipes = np.random.choice(recipes[0:8], size=110)
    elif m in machines[4:8]:   # Machines 5-8 specialize in R_09 to R_16
        m_recipes = np.random.choice(recipes[8:16], size=110)
    else:                      # Machines 9-10 specialize in R_17 to R_20
        m_recipes = np.random.choice(recipes[16:20], size=110)

    df_m = pd.DataFrame({
        'Datetime': m_times,
        'machine_id': m,
        'recipe_id': m_recipes,
        'lot_id': [f'LOT_{np.random.randint(100000, 999999)}' for _ in range(110)],
        'lot_qty': np.random.randint(50, 500, size=110)
    })
    df_list.append(df_m)

# Combine into one master dataframe and shuffle order to simulate raw logs
df_raw = pd.concat(df_list).sample(frac=1).reset_index(drop=True)


# ==========================================
# STEP 2: SHIFT WITHIN GROUPS TO ENSURE LOGICAL CONTINUITY
# ==========================================
MAX_GAP = pd.Timedelta(hours=12)

# Sort chronologically to align handoffs
df_sorted = df_raw.sort_values(by='Datetime').copy()

# Group by machine id ONLY for the sequence tracking step
df_group = df_sorted.groupby('machine_id')
df_sorted['next_recipe_id'] = df_group['recipe_id'].shift(-1)
df_sorted['next_datetime'] = df_group['Datetime'].shift(-1)
df_sorted['time_elapsed'] = df_sorted['next_datetime'] - df_sorted['Datetime']

# Sever links that represent long machine downtime gaps
valid_transition_mask = (
    df_sorted['next_recipe_id'].notna() &
    (df_sorted['time_elapsed'] <= MAX_GAP)
)
df_transitions = df_sorted[valid_transition_mask].copy()


# ==========================================
# STEP 3: COMPUTE MACHINE-INDEPENDENT GLOBAL PROBABILITIES
# ==========================================
# Aggregate ALL valid transitions together across the entire pool
counts = pd.crosstab(df_transitions['recipe_id'], df_transitions['next_recipe_id'])

# Guarantee a square matrix containing all 20 recipes
counts = counts.reindex(index=recipes, columns=recipes, fill_value=0)

# Normalize globally across rows (Row sum = 1.0 probability)
global_matrix = counts.div(counts.sum(axis=1).clip(lower=1), axis=0)


# ==========================================
# STEP 4: BUILD GLOBAL NETWORKX DIRECTED GRAPH
# ==========================================
G = nx.DiGraph()

# Add edges using the global probability pool
for from_recipe in global_matrix.index:
    for to_recipe in global_matrix.columns:
        prob = global_matrix.loc[from_recipe, to_recipe]
        if prob > 0:
            G.add_edge(from_recipe, to_recipe, weight=prob)


# ==========================================
# STEP 5: RUN NETWORK ANALYTICS SUBGROUP DETECTION
# ==========================================
print(f"Total Combined Valid Transitions Processed: {len(df_transitions)}")
print("\n--- DETECTED HARD BOUNDARIES ---")
# Weakly connected components capture structural voids where systems never touch
hard_clusters = list(nx.weakly_connected_components(G))
for i, cluster in enumerate(hard_clusters, 1):
    print(f"Isolated Hard Ecosystem {i}: {sorted(list(cluster))}")

print("\n--- DETECTED SOFT COMMUNITIES ---")
# Louvain finds optimal communities within those hard islands based on probability density
soft_communities = community.louvain_communities(G, weight='weight', seed=42)
for i, comm in enumerate(soft_communities, 1):
    print(f"Soft Production Profile {i}: {sorted(list(comm))}")


# ==========================================
# STEP 6: VISUALIZE LARGE NETWORK RELATIONSHIPS
# ==========================================
plt.figure(figsize=(12, 9))

# Use Kamada-Kawai layout; it spaces independent components out clean and wide
pos = nx.kamada_kawai_layout(G)

# Dynamically color nodes by soft community assignment
community_map = {node: i for i, comm in enumerate(soft_communities) for node in comm}
node_colors = [community_map.get(node, 0) for node in G.nodes()]

# Draw structural recipe nodes
nx.draw_networkx_nodes(G, pos, node_size=700, node_color=node_colors, cmap=plt.cm.Accent, edgecolors='black')

# Separate edges to prevent overlay mess
standard_edges = [(u, v) for u, v in G.edges() if u != v]

# Draw standard directed lines (thin with alpha transparency for high density)
nx.draw_networkx_edges(G, pos, edgelist=standard_edges, arrowstyle='->', arrowsize=12,
                       edge_color='gray', width=0.8, alpha=0.6, connectionstyle='arc3,rad=0.1')

# Add high-contrast text labels
nx.draw_networkx_labels(G, pos, font_size=8, font_weight='bold')

plt.title("Global Recipe Transition Network Map (1,100 Transactions Pooled)\nDistinct spatial groups indicate hard boundaries. Node colors show soft communities.", fontsize=12, fontweight='bold')
plt.axis('off')
plt.tight_layout()
plt.show()

